name: "Documentation"
on:
  push: 
    branches:
      - "support/pr-stat"
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  documentation:
    runs-on: ubuntu-latest
    container: quay.io/operator_testing/community-operators-mkdocs
    steps:
    - uses: actions/checkout@v2
    - name: What OS is running
      run: uname -a
    - name: generate docs
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        ci/operator-flow/doc.sh 5000
        mkdocs build
        ls -al
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./site
